# Site
repository: Etrama/etrama.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Kaushik Moudgalya_change_trial
title: Machine Learning Enthusiast
email: kaushikmoudgalya@gmail.com
website: etrama.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: Banana_Leopard
github_username:  Etrama
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: kaushik-gowrishankar-moudgalya
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi there! I'm Kaushik and I dabble in Machine Learning, scripting, and DevOps. I'm a Consultant (Solution Advisor) at my day job.
  Check out my projects or one of my textbook / paper summaries!
  
  |Interests &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: <mark>Machine Learning</mark> <mark>Deep Learning</mark> <mark>Gamifying and Accelerating Learning</mark>
  |Libraries &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: <mark>FastAI</mark> <mark>PyTorch</mark> <mark>Numpy</mark> <mark>Scipy</mark> <mark>Pandas</mark>  <mark>Keras</mark>  <mark>Prophet</mark>  <mark>Sklearn</mark>  <mark>Plotly Dash</mark> <mark>TPOT</mark>
  |Languages&nbsp;: <mark>Python</mark> <mark>Shell Scripting</mark> <mark>MATLAB</mark> <mark>VBA</mark> <mark>Javascript</mark>
  |Skills &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: <mark>Machine Learning</mark> <mark>RPA</mark> <mark>Oracle EBS and Cloud Security</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About
more_content: | # this will include new lines to allow paragraphs
  In my free time I will usually: 
    - Watch anime / read manga
    - Exercise
    - Work on some pet project / jump from one hobby to another
    - Learn a language. I can speak a lot of languages- English, Hindi, Marathi, Tamil, French (B2), German (B1.1) and a bit of Japanese (N5.1).

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 

