# Site
repository: Etrama/etrama.github.io
favicon: images/favicon.ico

# Personal info
name: Kaushik Moudgalya
title: Machine Learning Enthusiast
email: kaushikmoudgalya@gmail.com
website: etrama.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: Banana_Leopard
github_username:  Etrama
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: Kaushik Moudgalya
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi there! I'm Kaushik and I dabble in ML, scripting, and DevOps. I'm a Consultant (Solution Advisor) at my day job.
  Check out my projects or one of my textbook / paper summaries!
  
  |Interests: <mark>Machine Learning</mark> <mark>Deep Learning</mark> <mark>Gamifying and Accelerating Learning</mark>
  |Libraries: <mark>FastAI</mark> <mark>PyTorch</mark> <mark>Numpy</mark> <mark>Scipy</mark> <mark>Pandas</mark>  <mark>Keras</mark>  <mark>Prophet</mark>  <mark>Sklearn</mark>  <mark>Plotly Dash</mark> <mark>TPOT</mark>
  |Languages: <mark>Python</mark> <mark>Shell Scripting</mark> <mark>MATLAB</mark> <mark>VBA</mark> <mark>Javascript</mark>
  |Skills &nbsp;&nbsp;&nbsp;&nbsp;: <mark>Machine Learning</mark> <mark>RPA</mark> <mark>Oracle EBS and Cloud Security</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me22222
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 

